// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Information: typeof import('./src/components/information.vue')['default']
    NPuzzle: typeof import('./src/components/n-puzzle.vue')['default']
  }
}

export { }
